// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class AppAttestFlutterError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "AppAttestFlutterError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? AppAttestFlutterError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// State snapshot returned to Dart. The Dart-side enum mapping happens
/// in `appattest_flutter.dart`; this class is the wire shape only.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AppAttestStatePayload {
  var name: String
  var errorCode: String? = nil
  var errorMessage: String? = nil
  /// `subscription_required` only.
  var errorSubscribeUrl: String? = nil
  /// `credits_required` only.
  var errorTopupUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppAttestStatePayload? {
    let name = pigeonVar_list[0] as! String
    let errorCode: String? = nilOrValue(pigeonVar_list[1])
    let errorMessage: String? = nilOrValue(pigeonVar_list[2])
    let errorSubscribeUrl: String? = nilOrValue(pigeonVar_list[3])
    let errorTopupUrl: String? = nilOrValue(pigeonVar_list[4])

    return AppAttestStatePayload(
      name: name,
      errorCode: errorCode,
      errorMessage: errorMessage,
      errorSubscribeUrl: errorSubscribeUrl,
      errorTopupUrl: errorTopupUrl
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      errorCode,
      errorMessage,
      errorSubscribeUrl,
      errorTopupUrl,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AppAttestStatePayload.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AppAttestStatePayload {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Host API — methods implemented natively in `AppAttestPlugin.swift` and
/// called from Dart via the generated `AppAttestHostApi`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppAttestHostApi {
  /// Synchronous, idempotent setup. Zero-argument (bucket is
  /// AAGUID-derived server-side).
  func start(completion: @escaping (Result<Void, Error>) -> Void)
  /// Awaits a terminal state. Resolves on `ready`; throws on
  /// subscriptionRequired / creditsRequired / unavailable.
  func waitForReady(completion: @escaping (Result<Void, Error>) -> Void)
  /// Re-runs the background sync.
  func retry(completion: @escaping (Result<Void, Error>) -> Void)
  /// Wipes stored credentials and secrets.
  func reset(completion: @escaping (Result<Void, Error>) -> Void)
  /// Invalidate the cached secrets bundle and immediately sync. Keeps
  /// attestation credentials; forces a 200 (1 credit on production).
  /// Use for "force refresh" / "sync now" UX.
  func invalidateBundle(completion: @escaping (Result<Void, Error>) -> Void)
  /// Synchronous-feeling secret lookup. Returns `null` if not yet
  /// synced or absent.
  func getSecret(name: String, completion: @escaping (Result<String?, Error>) -> Void)
  /// Snapshot of every synced secret as `{ name: value }`.
  func getAllSecrets(completion: @escaping (Result<[String: String], Error>) -> Void)
  /// Current state snapshot.
  func getState(completion: @escaping (Result<AppAttestStatePayload, Error>) -> Void)
  /// Set runtime mode. `null`/`"production"` for production;
  /// `"local"` for DEBUG-only previews/simulator. `"sandbox"`
  /// is not valid (use a real dev/TestFlight build).
  func setDebugMode(name: String?, stubs: [String: String]?, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppAttestHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AppAttestHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppAttestHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Synchronous, idempotent setup. Zero-argument (bucket is
    /// AAGUID-derived server-side).
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.appattest_flutter.AppAttestHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        api.start { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// Awaits a terminal state. Resolves on `ready`; throws on
    /// subscriptionRequired / creditsRequired / unavailable.
    let waitForReadyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.appattest_flutter.AppAttestHostApi.waitForReady\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      waitForReadyChannel.setMessageHandler { _, reply in
        api.waitForReady { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      waitForReadyChannel.setMessageHandler(nil)
    }
    /// Re-runs the background sync.
    let retryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.appattest_flutter.AppAttestHostApi.retry\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      retryChannel.setMessageHandler { _, reply in
        api.retry { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      retryChannel.setMessageHandler(nil)
    }
    /// Wipes stored credentials and secrets.
    let resetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.appattest_flutter.AppAttestHostApi.reset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetChannel.setMessageHandler { _, reply in
        api.reset { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resetChannel.setMessageHandler(nil)
    }
    /// Invalidate the cached secrets bundle and immediately sync. Keeps
    /// attestation credentials; forces a 200 (1 credit on production).
    /// Use for "force refresh" / "sync now" UX.
    let invalidateBundleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.appattest_flutter.AppAttestHostApi.invalidateBundle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invalidateBundleChannel.setMessageHandler { _, reply in
        api.invalidateBundle { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      invalidateBundleChannel.setMessageHandler(nil)
    }
    /// Synchronous-feeling secret lookup. Returns `null` if not yet
    /// synced or absent.
    let getSecretChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.appattest_flutter.AppAttestHostApi.getSecret\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSecretChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        api.getSecret(name: nameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSecretChannel.setMessageHandler(nil)
    }
    /// Snapshot of every synced secret as `{ name: value }`.
    let getAllSecretsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.appattest_flutter.AppAttestHostApi.getAllSecrets\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllSecretsChannel.setMessageHandler { _, reply in
        api.getAllSecrets { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAllSecretsChannel.setMessageHandler(nil)
    }
    /// Current state snapshot.
    let getStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.appattest_flutter.AppAttestHostApi.getState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStateChannel.setMessageHandler { _, reply in
        api.getState { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getStateChannel.setMessageHandler(nil)
    }
    /// Set runtime mode. `null`/`"production"` for production;
    /// `"local"` for DEBUG-only previews/simulator. `"sandbox"`
    /// is not valid (use a real dev/TestFlight build).
    let setDebugModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.appattest_flutter.AppAttestHostApi.setDebugMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDebugModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg: String? = nilOrValue(args[0])
        let stubsArg: [String: String]? = nilOrValue(args[1])
        api.setDebugMode(name: nameArg, stubs: stubsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setDebugModeChannel.setMessageHandler(nil)
    }
  }
}
